org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# --- Версии зависимостей ---
versionMapsforgeCore=0.20.0
versionMapsforgeMap=0.20.0
versionMapsforgeMapAndroid=0.20.0
versionPlayServicesLocation=21.3.0
versionRoom=2.6.1
versionLifecycle=2.8.4
versionCoroutines=1.8.1
versionMaterial=1.12.0
versionCoreKtx=1.13.1
versionAppcompat=1.7.0
